# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies for react 
      run: cd autoTest/react && npm install
    - name: Install dependencies for puppeteer
      run: cd autoTest/pptr && npm install
    - name: Run react project
      run: cd autoTest/react && npm run start &
    - name: Run puppeteer
      run: cd autoTest/pptr && node node_modules/puppeteer/install.js && node index.js >> temp.txt && cat temp.txt
    - name: Check output
      run: cd autoTest/pptr && grep "End Test Suite{{':'}} Result{{':'}} Failed" temp.txt && if [[ "$?" == 0 ]]; then echo success; else echo fail; fi
